clean:
whatver:
thisasarg
rgerwgqer qew qwer qwer qwt qwer
eitherrqwerqwe qwe

ewqr werqwe rqwe rqwer qwe

 qw eitherqw ewqrw error_msgqw
  rqwee rqwe q
  we rqwewe
  qwe
  qwe rqweqw rqweqwe rqweqwe rqwerqwfsdfas

verify:

compress:
uncompress:
dfegqwet