#! /bin/bash
#   run_be_checks: Runs scheck, full_lvs and for digital designs cvc-rv.

#   Copyright 2022 D. Mitch Bailey  cvc at shuharisystem dot com

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   
#       http://www.apache.org/licenses/LICENSE-2.0
#   
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Overview:
#  1. Run hierarchy check
#  2. Run soft connection check
#  3. Run full lvs
#  4. Run cvc for digital designs
#  
#  All variable specified in LVS configuration file

# Usage
# run_be_checks LVS_config_file [top_netlist [top_layout]] 		: extract, then check
# run_be_checks --noextract LVS_config_file [top_netlist [top_layout]]	: use previous extraction results to compare

if [[ $1 = "--noextract" ]]; then
	export EXTRACT_LAYOUT=no
	shift
else
	export EXTRACT_LAYOUT=yes
fi
	
if [[ $# -lt 1 || $# -gt 3 ]]; then
	echo "usage: run_be_checks [--noextract] lvs_config_file [netlist_top [layout_top]]"
	exit 1
fi

CONFIG_FILE=$1
TOP_SOURCE=$2
TOP_LAYOUT=${3:-$TOP_SOURCE}

if [[ ! -f $CONFIG_FILE ]]; then
	echo "Could not find LVS configuration file $CONFIG_FILE"
	exit 1
fi

#get_lvs_config $CONFIG_FILE | 
	source $CONFIG_FILE
if [[ $EXTRACT_LAYOUT = no ]]; then
	export LAYOUT_FILE=
fi

echo "TOP SOURCE: $TOP_SOURCE"
echo "SOURCE FILE(S): $LVS_SPICE_FILES $LVS_VERILOG_FILES"
echo "TOP LAYOUT: $TOP_LAYOUT"
echo "LAYOUT FILE: $LAYOUT_FILE"

: "${LOG_ROOT:=$(pwd)/$TOP_SOURCE}"
: "${LVS_ROOT:=$(pwd)}"
: "${SIGNOFF_ROOT:=$(pwd)/$TOP_SOURCE}"
: "${WORK_ROOT:=$(pwd)/$TOP_SOURCE}"
export LOG_ROOT LVS_ROOT SIGNOFF_ROOT WORK_ROOT

if [[ ! -d $WORK_ROOT ]]; then
	mkdir -p $WORK_ROOT/$TOP_SOURCE 
	mkdir -p $WORK_ROOT/$TOP_LAYOUT
fi

$LVS_ROOT/run_hier_check $TOP_SOURCE "$LVS_VERILOG_FILES" $TOP_LAYOUT $LAYOUT_FILE

$LVS_ROOT/run_scheck $CONFIG_FILE $TOP_LAYOUT $LAYOUT_FILE

$LVS_ROOT/run_full_lvs --noextract $CONFIG_FILE $TOP_SOURCE $TOP_LAYOUT

if [[ $TOP_SOURCE = "user_project_wrapper" ]]; then
	$LVS_ROOT/run_cvc $TOP_LAYOUT
fi

echo "
Soft check result:"
tail -n 20 $LOG_ROOT/$TOP_LAYOUT/soft.log | awk '/Final result/,/Logging/' | grep -v ^Logging

echo "
LVS result:"
tail -n 20 $LOG_ROOT/$TOP_SOURCE/lvs.log | awk '/Final result/,/^END/' | grep -v ^Logging | grep -v "^END"

if [[ $TOP_SOURCE = "user_project_wrapper" ]]; then
	echo "
CVC result:"
	grep 'CVC: Total:' $LOG_ROOT/$TOP_LAYOUT/cvc.log
fi
	
