#! /bin/bash

: "${LVS_ROOT:=$(pwd)}"
: "${LOG_ROOT:=$(pwd)}"
: "${SIGNOFF_ROOT:=$(pwd)}"
: "${WORK_ROOT:=$(pwd)}"
export LVS_ROOT LOG_ROOT SIGNOFF_ROOT WORK_ROOT

export DESIGN_NAME=$1
export RESULTS_DIR=$WORK_ROOT/$DESIGN_NAME/ext

echo " "
echo "Running CVC..."

if [[ ! -f $RESULTS_DIR/$DESIGN_NAME.cdl.gz ]]; then
	if [[ ! -f $RESULTS_DIR/$DESIGN_NAME.gds.spice ]]; then
		echo "Could not create cdl file from $RESULTS_DIR/$DESIGN_NAME.gds.spice"
		exit 1
	else
		echo "Creating $RESULTS_DIR/$DESIGN_NAME.cdl"
		$LVS_ROOT/spi2cdl $RESULTS_DIR/$DESIGN_NAME.gds.spice |
			gzip -c >$RESULTS_DIR/$DESIGN_NAME.cdl.gz
	fi
fi

BASE_NAME=${DESIGN_NAME//[A-Z0-9][A-Z0-9]_/} # remove leading 2 byte prefices
if [[ (! -f $WORK_ROOT/$DESIGN_NAME/$DESIGN_NAME.power) && -f $LVS_ROOT/cvc/$BASE_NAME.$PDK.power ]]; then
	cp $LVS_ROOT/cvc/$BASE_NAME.$PDK.power $WORK_ROOT/$DESIGN_NAME/$DESIGN_NAME.power
fi

start_time=$SECONDS
cvc $LVS_ROOT/cvc/cvcrc.$PDK

runtime=$((SECONDS - start_time))
hours=$((runtime / 3600))
minutes=$(((runtime % 3600) / 60))
seconds=$(((runtime % 3600) % 60))
printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >>$WORK_ROOT/$DESIGN_NAME/cvc.log

if [[ $WORK_ROOT != $LOG_ROOT ]]; then
	cp $WORK_ROOT/$DESIGN_NAME/cvc.log $LOG_ROOT/$DESIGN_NAME/.
fi
if [[ $WORK_ROOT != $SIGNOFF_ROOT ]]; then
	cp $WORK_ROOT/$DESIGN_NAME/cvc.log $SIGNOFF_ROOT/$DESIGN_NAME/.
fi
